### ISSUE TITLE
Coding style 

### ISSUE THREAD

**Issue by golgoth13** [ayzoh/webcam_capture#3]
Pour ma part, je m'impose le coding style du noyau linux : j'ai pas l'impression que se soit le cas (mais avec mon portable difficile de juger les bonnes indentations). Par contre il y a des intentations non respectées. On ne déclare pas non plus une variable de boucle (i) hors de la boucle et on essaye de lui donner un nom plus explicite que i. J'ai vu des "calloc" mais pas de "free" : un petit coup de valgrind devrais te dire si tu n'as pas de fuites mémoires

**Comment by ayzoh** [comment]
Pour la norme, j'utilise une config emacs spécifique a mon école, si elle ne convient pas je peux évidemment changer. J'ai normalement réglé les issues, j'attends un feedback sur mes derniers commit !
